---
swagger: "2.0"
info:
  title: GFE REST Services
  description: |
    REST services for curating and computing with GFE
  version: 0.1.0
  contact:
    email: cibmtr-pypi@nmdp.org
  license:
    name: GNU Lesser General Public License version 3
    url: https://opensource.org/licenses/lgpl-3.0.html
tags:
  - name: IMGT
    description: "Available IMGT DB releases"
  - name: "Sequence Annotation"
    description: "Annotation by sequence"
  - name: Features
    description: "Features associated with a locus"
  - name: GFE
    description: Create and Retrieve GFE
  - name: "KIR By GFE"
    description: "Return Kir response by GFE"
paths:
  /imgt-versions:
    get:
      summary: Get available IMGT DB versions
      tags:
        - IMGT
      operationId: allreleases_get
      consumes:
        - "application/json"
      responses:
        200:
          description: "OK"
        404:
          description: "Failed to load all db releases"
      x-swagger-router-controller: "api.controllers.all_releases_controller"

  /annotation/{locus}:
    post:
      summary: Annotate a sequence for a locus
      tags:
        - "Sequence Annotation"
      operationId: gfeAnnotation_post
      consumes:
        - "application/json"
      parameters:
        - name: locus
          in: path
          description: "Valid HLA locus"
          required: true
          type: string
        - name: gene_family
          description: "Gene Family, eg: HLA, KIR"
          type: string
          in: query
          required: false
        - in: body
          name: sequence
          required: true
          description: Sequence to annotate
          schema:
            type: object
            required:
              - sequence
            properties:
              sequence:
                type: string
                example:
                  AGAGACTCTCCCGAGGATTTCGTGTACCAGTTTAAGGCCATGTGCTACTTCACC
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Typing"
        404:
          description: "Failed to annotate the sequence"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "api.controllers.gfe_annotation_controller"

  /feature/{locus}:
    get:
      summary: Load All Features
      description: |
        For the given locus, retrieve all associated features.
        This will result in a large result.
      tags:
        - Features
      operationId: locusfeature_get
      produces:
        - "application/json"
      parameters:
        - name: locus
          in: path
          description: HLA locus
          required: true
          type: string
      responses:
        200:
          description: OK
        404:
          description: "Failed to load the features of locus"
      x-swagger-router-controller: "api.controllers.locus_feature_controller"

  /gfe/{locus}:
    put:
      tags:
        - GFE
      operationId: "gfecreate_post"
      consumes:
        - "application/json"
      parameters:
        - name: locus
          in: path
          description: Valid HLA locus
          required: true
          type: string
        - name: imgt_version
          in: query
          description: IMGT/HLA DB Version
          required: true
          type: string
          default: "3.31.0"
        - name: sequence
          in: body
          description: Consensus sequence
          required: true
          schema:
            type: object
            required:
              - sequence
            properties:
              sequence:
                type: string
                example:
                  ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Typing"
        404:
          description: Failed to create GFE from HLA sequence and locus
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "api.controllers.gfe_create_controller"

    get:
      summary: Get Alleles and their corresponding GFE By Locus and IMGT DB version
      tags:
        - "GFE"
      operationId: "releases_locus_get"
      consumes:
        - "application/json"
      parameters:
        - name: locus
          in: path
          description: "Valid locus name"
          required: true
          type: string
        - name: imgt_release_version
          in: query
          description: "Valid IMGT version "
          required: true
          type: string
          default: '3.36.0'
      responses:
        200:
          description: "OK"
        404:
          description: "Failed to get GFE and HLA for the IMGT version and locus"
      x-swagger-router-controller: "api.controllers.releases_by_locus_controller"


definitions:
  Error:
    type: object
    required:
      - "Message"
      - "gfedb_version"
      - "imgtdb_version"
      - "pygfe_version"
    properties:
      Message:
        type: string
      pygfe_version:
        type: string
      gfedb_version:
        type: string
      imgtdb_version:
        type: string
      log:
        type: array
        items:
          type: string
      type:
        type: string
  Typing:
    type: object
    properties:
      seqdiff:
        type: array
        items:
          $ref: "#/definitions/Seqdiff"
      protdiff:
        type: array
        items:
          $ref: "#/definitions/Seqdiff"
      features:
        type: array
        items:
          $ref: "#/definitions/Feature"
      novel_features:
        type: array
        items:
          $ref: "#/definitions/Feature"
      gfe:
        type: string
      hla:
        type: string
      closest_gfe:
        type: string
      full_gene_accession:
        type: integer
      differences:
        type: integer
      status:
        type: string
      pygfe_version:
        type: string
      gfedb_version:
        type: string
      imgtdb_version:
        type: string
    example:
      gfe: "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-1"
      hla: "HLA-A*01:01:01:01"
      G: "HLA-A*01:01:01G"
      lg: "HLA-A*01:01g"
      full_gene_accession: 10093
      closest_gfe: "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-1"
      differences: 10
      sequence_differences:
        - term: "intron"
          rank: 1
          pos: 10
          ref: "A"
          inseq: "G"
      protdiff:
        pos: 4
        location: "ARD"
        ref: "A"
        inseq: "G"
      status: "novel"
      features:
        - accession: 1
          locus: "HLA-A"
          rank: 1
          term: "exon"
          sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
        - accession: 2
          locus: "HLA-A"
          rank: 1
          sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
          term: "exon"
      act_version: "0.0.1"
      gfe_version: "0.0.1"
      gfedb_version: "0.0.1"
  Seqdiff:
    type: object
    properties:
      term:
        type: string
      rank:
        type: integer
      location:
        type: integer
      ref:
        type: string
      inseq:
        type: string
    example:
      term: "intron"
      rank: 1
      pos: 10
      ref: "A"
      inseq: "G"
  Feature:
    type: object
    properties:
      accession:
        type: integer
      rank:
        type: integer
      sequence:
        type: string
      term:
        type: string
    example:
      accession: 1
      locus: "HLA-A"
      rank: 1
      sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
      term: "exon"
